### ISSUE TITLE
Bug: Game page always opens to Title Card

### ISSUE THREAD

**Issue by theredwillow** [joshzcold/Cold-Family-Feud#72] opened 2024-01-27 02:30 UTC
When an admin has a game already in progress and opens a new game window, it opens to the title card instead of the round that they are currently on.

**Comment by joshzcold** [comment] 2024-01-28 21:58
I wasn't able to reproduce on this one. 

Can you list of specific steps?

I tried switching the rounds before opening the game window and did the same with fast money without reproducing.

Maybe has to do with browser caching on `/game` page.

**Comment by theredwillow** [comment] 2024-01-29 05:19
I've seen something similar with caching that involved playing with these settings on the backend. https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Cache-Control

I don't feel very strong in this subject. I'll need to read up on https://nextjs.org/docs/app/building-your-application/caching

**Comment by karlromets** [comment] 2024-12-29 14:45
I have tried to reproduce as well but can't seem to make this pop up, so I can only theorize. In ws.js where we are processing game window connection, the order of events might cause a race condition to happen.

When you open a new game window:
1. The server adds the window to its connections
2. The server broadcasts the room data

But here is where the race condition might happen, because this all happens when you open the game window, the window's websocket message handler might not yet be fully ready to receive messages yet. Which means if we broadcast before being ready, we aren't able to get the data and are left with the initial game object. This makes sense because the initial game object has `title: true`.

And I have now realized this again shouldn't be possible since the game window will not show title screen is game.teams is null. 😅

```js
} else if (message.action === "game_window") {
  let [room_code, user_id] = message.session.split(":");
  rooms[room_code].connections[`game_window_${uuidv4()}`] = ws;
  wss.broadcast(
    room_code,
    JSON.stringify({ action: "data", data: rooms[room_code].game }),
  );
}
```

@theredwillow in the browser network tab you can disable caching and see if that solves it, then we know it's likely a caching issue, also does this happen every time you open a new game window or rarely?

**Comment by karlromets** [comment] 2024-12-29 15:18
Okay, it seems message handler is setup before the game_window action, which makes my guess wrong. Tried loading the game window with throttling as well and every bit of data that I get gives me game state with title:false. Can't reproduce.

**Comment by joshzcold** [comment] 2024-12-29 16:17
Closing, please reopen if you run into it again.

**Closed by joshzcold** 2024-12-29 16:17 UTC
